document.getElementById('sunchu').addEventListener('tap',function(){
	console.info("33333333");
	mui.openWindow({
		url:'../chatDemo2/chat-sunchu-to-lisi.html',
		id:'sunchu'
	});
});
document.getElementById('zhangsan').addEventListener('tap',function(){
	console.info("33333333");
	mui.openWindow({
		url:'../chatDemo2/chat-zhangsan-to-lisi.html',
		id:'zhangsan'
	});
});
document.getElementById('lisi').addEventListener('tap',function(){
	console.info("33333333");
	mui.openWindow({
		url:'../chatDemo2/chat-lisi-to-zhangsan.html',
		id:'lisi'
	});
});
